### ISSUE TITLE
Integrate analytics in website

### ISSUE THREAD

**Issue by nitishMehrotra** [nitishMehrotra/PnPWebsite#8]

**Comment by aggarwalakhil9** [comment]
google analytics have been integrated. 
Steps required: 
1. using your google account, sign up for google analytics at analytics.google.com
2. get a tracking id. this id is unique to your account and must be used further for integration.

Further there are 2 ways for integration:
1A. there is sample html code provided by google analytics to integrate into your html pages (all html pages if you want to run analytics on all your pages, else wherever required)
1B. replace the tracking id in your code with your unique tracking code. 

2A. wordpress has several plugins available (free) which do this integration for you. Install any one (I used one by Kevin Sylvester. It automatically creates a directory called "google analytics" under wp-content/plugins/
2B. in wordpress admin page under Settings, we need to update the Google Analytics settings available under Plugings tab. Update your tracking id there.

For our current website, we used second approach as it was more cleaner way of doing it rather than putting html code in every pho file.
